export { default as AuthService } from './AuthService'
export { default as UserService } from './UserService'
export { default as DisciplineService } from './DisciplineService'
export { default as DisciplineNoteService } from './DisciplineNoteService'
export { default as DisciplineStudentService } from './DisciplineStudentService'
